# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11 for compile
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          check-latest: false
      - name: Compile
        run: mvn clean package -DskipTests -P CI --batch-mode --quiet
      - name: Setup JDK ${{ matrix.java }} for running
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          check-latest: false
      - name: Version
        run: java -version
