# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jdk8:
    runs-on: ubuntu-latest
    name: Java 8 job
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          check-latest: false
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          check-latest: false
      - name: Version
        run: java -version
      - name: Compile
        run: mvn clean install -DskipTests --batch-mode --quiet --global-toolchains ./toolchains.xml
  jdk11:
    runs-on: ubuntu-latest
    name: Java 11 job
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          check-latest: false
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          check-latest: false
      - name: Version
        run: java -version
      - name: Compile
        run: mvn clean install -DskipTests --batch-mode --quiet --global-toolchains ./toolchains.xml


